# name: my-app

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-frontend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Build and push frontend Docker image
#         run: |
#           docker build -t trungdt1718/my-shop-frontend:latest ./frontend
#           docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
#           docker push trungdt1718/my-shop-frontend:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: [ build-frontend]
#     steps:
#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_PRIVATE_KEY }}
#           script: |
#             docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
           
#             # Deploy frontend
#             docker pull trungdt1718/my-shop-frontend:latest
#             docker stop my-shop-frontend-container || true
#             docker rm my-shop-frontend-container || true
#             docker run -d -p 5173:80 --name my-shop-frontend-container trungdt1718/my-shop-frontend:latest

name: my-app

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Navigate to Frontend Directory
        run: cd frontend
        
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t trungdt1718/my-shop-frontend:latest ./frontend
      - name: Publish image to docker hub
        run: docker push trungdt1718/my-shop-frontend:latest   

  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:
      - name: Pull image from docker hub
        run: docker pull trungdt1718/my-shop-frontend:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer trungdt1718/my-shop-frontend   